### ISSUE TITLE
Autoimporting KiCad pretty footprints from hardware/*.sch

### ISSUE THREAD

**Issue by brainstorm** [cnlohr/esplocalizer#2]
Hello @cnlohr,

Thanks much for publishing your projects as open hardware as well as the firmware, always inspiring stuff to learn from you.

I have been trying to reuse your `.sch` since I have a couple of modifications in mind to your design. 

Sorry if this sounds obvious (I'm a relatively new KiCad user), but how can I auto-import the footprints for pcbnew without manually importing each `.pretty` library/module? as the KiCad docs state, i.e:

https://github.com/jdunmire/kicad-ESP8266

I thought about giving this giant meta-pretty-repo a shot, but the ESP footprint doesn't seem to be there:

https://github.com/monostable/kicad_footprints

I understand you might be using your existing installation/footprints from past projects, but what would be your advice to semi-automate this process of importing footprints?

**Comment by brainstorm** [comment]
I also meant including the `.pro`, `.lib`, etc files from KiCad like in the ESPUSB project:

https://github.com/cnlohr/espusb/tree/master/hardware/usb_8285

Also, totally understand if you don't want to release those yet before monetizing some boards a bit more through ebay, happy to start from scratch myself instead ;)

**Comment by brainstorm** [comment]
Hold on a minute... you are adding LoRa (RFM95W radio) to a sister board, that is so cool!!! Exactly what I wanted to do for my own board!

![screen shot 2017-01-06 at 18 23 00](https://cloud.githubusercontent.com/assets/175587/21726510/46ff1d2a-d43d-11e6-9982-ddf203908cc8.png)

Closing this issue since I'm going on my own with KiCad from scratch, but would really appreciate forking/refactoring esplocalizer's hardware (instead of dealing with `??` and unresolved symbols/components from the bare `.sch` file)... is there a kicad-utils script or similar that helps resolving/downloading those?

**Comment by cnlohr** [comment]
That seems odd... It should be able to pull the footprints from the cache.   Perhaps I forgot to include the cache?

**Comment by cnlohr** [comment]
Looks like I did!  Fixed.

**Comment by brainstorm** [comment]
Awesome, thanks Charles! The eeschema looks great now with the cached file (no more `??`'d components). The netlist can be generated without problems but it seems like `Cvpcb` is not liking the part assignments/mappings:

![screen shot 2017-01-09 at 11 32 11](https://cloud.githubusercontent.com/assets/175587/21763711/9282ab26-d65f-11e6-85f6-bb9df37c492b.png)
![screen shot 2017-01-09 at 11 33 48](https://cloud.githubusercontent.com/assets/175587/21763710/928284b6-d65f-11e6-8926-43ee5f265f3a.png)

**Comment by cnlohr** [comment]
I believe most of them are in my public repository here: https://cnlohr.net/pubsvn/electrical/kicad/

Did you tell KiCad to download all footprints locally?  If not, you should.  It should give you the common parts like SM0603 and SOT23-5

**Comment by brainstorm** [comment]
Thanks Charles for following this up, super appreciated.

I found that svn a while later exploring, but then I switched to building my own board from scratch since I want to remove/change quite a few components and get more acquainted with KiCad.

Btw, if you ever move that repo to github, let me know, happy to include it to this semi-automated community repo, I've been using it recently, really handy:

https://github.com/monostable/kicad_footprints

**Comment by cnlohr** [comment]
I might, but, it's one of those things I like to keep on my own because I know where everything I need is.
